Update bump-version.yml

diff --git a/.github/workflows/bump-version.yml b/.github/workflows/bump-version.yml
--- a/.github/workflows/bump-version.yml
+++ b/.github/workflows/bump-version.yml
@@ -24,7 +24,7 @@ jobs:
       - name: 🚀 Bump Version
         id: bump
         run: |
-          npm run bump-version || (echo "BUMP_FAILED=true" >> $GITHUB_OUTPUT && exit 1)
+          npm run bump-version || (echo "BUMP_FAILED=true" >> $GITHUB_OUTPUT && exit)
           echo "BUMP_FAILED=false" >> $GITHUB_OUTPUT
           npm install
 
